### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pyspelling#1]
Things I'd like to accomplish before I officially start using this.  This obviously doesn't cover what may be included before this becomes stable, just what I want so I can start using it.

- [x] HTML filter should unescape HTML entities etc.
- [x] Python filter should avoid byte strings by default, for this reason, maybe we don't bother supporting PY2 so we don't have to detect if Unicode is being forced in them etc.  Not sure PY2 is low concern for me, I don't mind avoiding it all together.
- [x] Give filters the ability to ignore certain named tokens returned by the parser. For instance, maybe you want docstrings to be passed through a Markdown filter, but normal comments don't need to be.  When being passed a `SourceText` object, you could check the `type` and avoid normal comments.
- [x] Add a Markdown filter.
- [x] Handle HTML comments.

---

Let's also get:

- [x] Complete documents.
- [x] Ensure setup and manifest are proper.
- [x] Configure Travis for auto-deploy

...Anything else I think of.

**Comment by facelessuser** [comment]
Changes are in. We need to confirm that they all work.

**Comment by facelessuser** [comment]
Everything has been churning a bit, but I think I've settled on basic behavior for now.  Just need to finish up ensuring it packages up correctly and setup PyPI deployment.
